from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 488)
        MainWindow.setMinimumSize(QtCore.QSize(987, 488))
        MainWindow.setMaximumSize(QtCore.QSize(987, 488))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Logo/logo.ico"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 971, 431))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("font:\"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 70, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.display_src_path = QtWidgets.QLineEdit(self.groupBox)
        self.display_src_path.setGeometry(QtCore.QRect(140, 70, 271, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.display_src_path.setFont(font)
        self.display_src_path.setStyleSheet("")
        self.display_src_path.setReadOnly(True)
        self.display_src_path.setObjectName("display_src_path")
        self.display_target_path = QtWidgets.QLineEdit(self.groupBox)
        self.display_target_path.setGeometry(QtCore.QRect(140, 110, 271, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.display_target_path.setFont(font)
        self.display_target_path.setStyleSheet("")
        self.display_target_path.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.display_target_path.setReadOnly(True)
        self.display_target_path.setObjectName("display_target_path")
        self.btn_dir_toggle = QtWidgets.QPushButton(self.groupBox)
        self.btn_dir_toggle.setEnabled(False)
        self.btn_dir_toggle.setGeometry(QtCore.QRect(370, 10, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_dir_toggle.setFont(font)
        self.btn_dir_toggle.setStyleSheet("")
        self.btn_dir_toggle.setObjectName("btn_dir_toggle")
        self.btn_img_toggle = QtWidgets.QPushButton(self.groupBox)
        self.btn_img_toggle.setGeometry(QtCore.QRect(480, 10, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_img_toggle.setFont(font)
        self.btn_img_toggle.setStyleSheet("")
        self.btn_img_toggle.setObjectName("btn_img_toggle")
        self.btn_browse_src = QtWidgets.QPushButton(self.groupBox)
        self.btn_browse_src.setGeometry(QtCore.QRect(440, 70, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_browse_src.setFont(font)
        self.btn_browse_src.setStyleSheet("")
        self.btn_browse_src.setObjectName("btn_browse_src")
        self.btn_browse_target = QtWidgets.QPushButton(self.groupBox)
        self.btn_browse_target.setGeometry(QtCore.QRect(440, 110, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_browse_target.setFont(font)
        self.btn_browse_target.setStyleSheet("")
        self.btn_browse_target.setObjectName("btn_browse_target")
        self.display_selected_images = QtWidgets.QPlainTextEdit(self.groupBox)
        self.display_selected_images.setGeometry(
            QtCore.QRect(700, 70, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.display_selected_images.setFont(font)
        self.display_selected_images.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.CursorShape.SizeVerCursor))
        self.display_selected_images.setStyleSheet("")
        self.display_selected_images.setReadOnly(True)
        self.display_selected_images.setObjectName("display_selected_images")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(560, 70, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(290, 170, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.display_img_cnt = QtWidgets.QLineEdit(self.groupBox)
        self.display_img_cnt.setGeometry(QtCore.QRect(200, 170, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.display_img_cnt.setFont(font)
        self.display_img_cnt.setStyleSheet("")
        self.display_img_cnt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.display_img_cnt.setReadOnly(True)
        self.display_img_cnt.setPlaceholderText("")
        self.display_img_cnt.setObjectName("display_img_cnt")
        self.check_compress = QtWidgets.QCheckBox(self.groupBox)
        self.check_compress.setGeometry(QtCore.QRect(410, 170, 22, 22))
        self.check_compress.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_compress.setText("")
        self.check_compress.setObjectName("check_compress")
        self.theme_toggle_btn = QtWidgets.QPushButton(self.groupBox)
        self.theme_toggle_btn.setEnabled(False)
        self.theme_toggle_btn.setGeometry(QtCore.QRect(900, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.theme_toggle_btn.setFont(font)
        self.theme_toggle_btn.setStyleSheet("")
        self.theme_toggle_btn.setObjectName("theme_toggle_btn")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(0, 210, 971, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setGeometry(QtCore.QRect(320, 10, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setGeometry(QtCore.QRect(320, 40, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setGeometry(QtCore.QRect(160, 10, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_1)
        self.label_13.setGeometry(QtCore.QRect(160, 70, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_1)
        self.label_14.setGeometry(QtCore.QRect(160, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        self.label_15.setGeometry(QtCore.QRect(160, 100, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.check_blur = QtWidgets.QCheckBox(self.tab_1)
        self.check_blur.setGeometry(QtCore.QRect(110, 10, 22, 22))
        self.check_blur.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_blur.setText("")
        self.check_blur.setObjectName("check_blur")
        self.check_contour = QtWidgets.QCheckBox(self.tab_1)
        self.check_contour.setGeometry(QtCore.QRect(110, 40, 22, 22))
        self.check_contour.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_contour.setText("")
        self.check_contour.setObjectName("check_contour")
        self.check_detail = QtWidgets.QCheckBox(self.tab_1)
        self.check_detail.setGeometry(QtCore.QRect(110, 70, 22, 22))
        self.check_detail.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_detail.setText("")
        self.check_detail.setObjectName("check_detail")
        self.check_sharpen = QtWidgets.QCheckBox(self.tab_1)
        self.check_sharpen.setGeometry(QtCore.QRect(110, 100, 22, 22))
        self.check_sharpen.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_sharpen.setText("")
        self.check_sharpen.setObjectName("check_sharpen")
        self.check_emboss = QtWidgets.QCheckBox(self.tab_1)
        self.check_emboss.setGeometry(QtCore.QRect(270, 10, 22, 22))
        self.check_emboss.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_emboss.setText("")
        self.check_emboss.setObjectName("check_emboss")
        self.check_find_edges = QtWidgets.QCheckBox(self.tab_1)
        self.check_find_edges.setGeometry(QtCore.QRect(270, 40, 22, 22))
        self.check_find_edges.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_find_edges.setText("")
        self.check_find_edges.setObjectName("check_find_edges")
        self.check_smooth = QtWidgets.QCheckBox(self.tab_1)
        self.check_smooth.setGeometry(QtCore.QRect(270, 70, 22, 22))
        self.check_smooth.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_smooth.setText("")
        self.check_smooth.setObjectName("check_smooth")
        self.check_smooth_more = QtWidgets.QCheckBox(self.tab_1)
        self.check_smooth_more.setGeometry(QtCore.QRect(270, 100, 22, 22))
        self.check_smooth_more.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_smooth_more.setText("")
        self.check_smooth_more.setObjectName("check_smooth_more")
        self.check_edge_enhance = QtWidgets.QCheckBox(self.tab_1)
        self.check_edge_enhance.setGeometry(QtCore.QRect(480, 10, 22, 22))
        self.check_edge_enhance.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_edge_enhance.setText("")
        self.check_edge_enhance.setObjectName("check_edge_enhance")
        self.check_edge_enhance_more = QtWidgets.QCheckBox(self.tab_1)
        self.check_edge_enhance_more.setGeometry(QtCore.QRect(480, 40, 22, 22))
        self.check_edge_enhance_more.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.check_edge_enhance_more.setText("")
        self.check_edge_enhance_more.setObjectName("check_edge_enhance_more")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading |
                                   QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading |
                                   QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading |
                                   QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(10, 100, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading |
                                   QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.input_color = QtWidgets.QLineEdit(self.tab_2)
        self.input_color.setGeometry(QtCore.QRect(120, 10, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_color.setFont(font)
        self.input_color.setStyleSheet("")
        self.input_color.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.input_color.setMaxLength(3)
        self.input_color.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_color.setObjectName("input_color")
        self.input_contrast = QtWidgets.QLineEdit(self.tab_2)
        self.input_contrast.setGeometry(QtCore.QRect(120, 40, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_contrast.setFont(font)
        self.input_contrast.setStyleSheet("")
        self.input_contrast.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.input_contrast.setMaxLength(3)
        self.input_contrast.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_contrast.setObjectName("input_contrast")
        self.input_sharpness = QtWidgets.QLineEdit(self.tab_2)
        self.input_sharpness.setGeometry(QtCore.QRect(120, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_sharpness.setFont(font)
        self.input_sharpness.setStyleSheet("")
        self.input_sharpness.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.input_sharpness.setMaxLength(3)
        self.input_sharpness.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_sharpness.setObjectName("input_sharpness")
        self.input_brightness = QtWidgets.QLineEdit(self.tab_2)
        self.input_brightness.setGeometry(QtCore.QRect(120, 100, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_brightness.setFont(font)
        self.input_brightness.setStyleSheet("")
        self.input_brightness.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.input_brightness.setMaxLength(3)
        self.input_brightness.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_brightness.setObjectName("input_brightness")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(280, 10, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(150, 10, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("")
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.radio_thumbnail = QtWidgets.QRadioButton(self.tab_3)
        self.radio_thumbnail.setGeometry(QtCore.QRect(100, 10, 21, 20))
        self.radio_thumbnail.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_thumbnail.setText("")
        self.radio_thumbnail.setObjectName("radio_thumbnail")
        self.radio_default_size = QtWidgets.QRadioButton(self.tab_3)
        self.radio_default_size.setGeometry(QtCore.QRect(370, 10, 21, 20))
        self.radio_default_size.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_default_size.setText("")
        self.radio_default_size.setChecked(True)
        self.radio_default_size.setObjectName("radio_default_size")
        self.radio_custom_size = QtWidgets.QRadioButton(self.tab_3)
        self.radio_custom_size.setGeometry(QtCore.QRect(240, 10, 21, 20))
        self.radio_custom_size.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_custom_size.setText("")
        self.radio_custom_size.setObjectName("radio_custom_size")
        self.input_height = QtWidgets.QLineEdit(self.tab_3)
        self.input_height.setEnabled(False)
        self.input_height.setGeometry(QtCore.QRect(80, 50, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_height.setFont(font)
        self.input_height.setStyleSheet("")
        self.input_height.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.input_height.setMaxLength(4)
        self.input_height.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_height.setReadOnly(False)
        self.input_height.setObjectName("input_height")
        self.input_width = QtWidgets.QLineEdit(self.tab_3)
        self.input_width.setEnabled(False)
        self.input_width.setGeometry(QtCore.QRect(220, 50, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_width.setFont(font)
        self.input_width.setStyleSheet("")
        self.input_width.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.input_width.setMaxLength(4)
        self.input_width.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_width.setReadOnly(False)
        self.input_width.setObjectName("input_width")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(150, 50, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.radio_jpg = QtWidgets.QRadioButton(self.tab_4)
        self.radio_jpg.setGeometry(QtCore.QRect(70, 10, 21, 20))
        self.radio_jpg.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_jpg.setText("")
        self.radio_jpg.setObjectName("radio_jpg")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(10, 40, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(10, 70, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(10, 100, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(120, 10, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("")
        self.label_29.setObjectName("label_29")
        self.radio_jpeg = QtWidgets.QRadioButton(self.tab_4)
        self.radio_jpeg.setGeometry(QtCore.QRect(70, 40, 21, 20))
        self.radio_jpeg.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_jpeg.setText("")
        self.radio_jpeg.setObjectName("radio_jpeg")
        self.radio_png = QtWidgets.QRadioButton(self.tab_4)
        self.radio_png.setGeometry(QtCore.QRect(70, 70, 21, 20))
        self.radio_png.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_png.setText("")
        self.radio_png.setObjectName("radio_png")
        self.radio_jfif = QtWidgets.QRadioButton(self.tab_4)
        self.radio_jfif.setGeometry(QtCore.QRect(70, 100, 21, 20))
        self.radio_jfif.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_jfif.setText("")
        self.radio_jfif.setObjectName("radio_jfif")
        self.radio_default_format = QtWidgets.QRadioButton(self.tab_4)
        self.radio_default_format.setGeometry(QtCore.QRect(190, 10, 21, 20))
        self.radio_default_format.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_default_format.setText("")
        self.radio_default_format.setChecked(True)
        self.radio_default_format.setObjectName("radio_default_format")
        self.tabWidget.addTab(self.tab_4, "")
        self.btn_apply_edits = QtWidgets.QPushButton(self.groupBox)
        self.btn_apply_edits.setGeometry(QtCore.QRect(440, 370, 86, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_apply_edits.setFont(font)
        self.btn_apply_edits.setStyleSheet("")
        self.btn_apply_edits.setObjectName("btn_apply_edits")
        self.btn_reset_stop = QtWidgets.QPushButton(self.groupBox)
        self.btn_reset_stop.setGeometry(QtCore.QRect(880, 370, 86, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.btn_reset_stop.setFont(font)
        self.btn_reset_stop.setStyleSheet("")
        self.btn_reset_stop.setObjectName("btn_reset_stop")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(0, 400, 971, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.compress_slider = QtWidgets.QSlider(self.groupBox)
        self.compress_slider.setEnabled(False)
        self.compress_slider.setGeometry(QtCore.QRect(540, 170, 91, 21))
        self.compress_slider.setMouseTracking(False)
        self.compress_slider.setTabletTracking(False)
        self.compress_slider.setMaximum(100)
        self.compress_slider.setPageStep(5)
        self.compress_slider.setProperty("value", 0)
        self.compress_slider.setSliderPosition(0)
        self.compress_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.compress_slider.setTickPosition(
            QtWidgets.QSlider.TickPosition.TicksBelow)
        self.compress_slider.setTickInterval(20)
        self.compress_slider.setObjectName("compress_slider")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(460, 170, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("")
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.compress_quality = QtWidgets.QLineEdit(self.groupBox)
        self.compress_quality.setEnabled(False)
        self.compress_quality.setGeometry(QtCore.QRect(650, 170, 31, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.compress_quality.setFont(font)
        self.compress_quality.setStyleSheet("")
        self.compress_quality.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.compress_quality.setReadOnly(True)
        self.compress_quality.setPlaceholderText("")
        self.compress_quality.setObjectName("compress_quality")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Image Processor v2.0"))
        self.groupBox.setTitle(_translate("MainWindow", "Image Processor"))
        self.label.setText(_translate("MainWindow", "Image Directory"))
        self.label_2.setText(_translate("MainWindow", "Target Directory"))
        self.btn_dir_toggle.setText(
            _translate("MainWindow", "Select Directory"))
        self.btn_img_toggle.setText(_translate("MainWindow", "Select Images"))
        self.btn_browse_src.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Select source directory, images</span></p></body></html>"))
        self.btn_browse_src.setText(_translate("MainWindow", "Browse"))
        self.btn_browse_target.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Select target folder</span></p></body></html>"))
        self.btn_browse_target.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Selected Images"))
        self.label_4.setText(_translate("MainWindow", "Compress Image"))
        self.label_5.setText(_translate(
            "MainWindow", "Number Of Selected Images"))
        self.theme_toggle_btn.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Toggle theme is still in development.</span></p></body></html>"))
        self.theme_toggle_btn.setText(_translate("MainWindow", "DARK"))
        self.label_6.setText(_translate("MainWindow", "Blur"))
        self.label_7.setText(_translate("MainWindow", "Contour"))
        self.label_8.setText(_translate("MainWindow", "Detail"))
        self.label_9.setText(_translate("MainWindow", "Sharpen"))
        self.label_10.setText(_translate("MainWindow", "Edge Enhance"))
        self.label_11.setText(_translate("MainWindow", "Edge Enhance More"))
        self.label_12.setText(_translate("MainWindow", "Emboss"))
        self.label_13.setText(_translate("MainWindow", "Smooth"))
        self.label_14.setText(_translate("MainWindow", "Find Edges"))
        self.label_15.setText(_translate("MainWindow", "Smooth More"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_1), _translate("MainWindow", "Filters"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_1), _translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Select filters for images.</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Color"))
        self.label_17.setText(_translate("MainWindow", "Contrast"))
        self.label_18.setText(_translate("MainWindow", "Sharpness"))
        self.label_19.setText(_translate("MainWindow", "Brightness"))
        self.input_color.setPlaceholderText(_translate("MainWindow", "1"))
        self.input_contrast.setPlaceholderText(_translate("MainWindow", "1"))
        self.input_sharpness.setPlaceholderText(_translate("MainWindow", "1"))
        self.input_brightness.setPlaceholderText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("MainWindow", "Enhancements"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Select enhancements for images.</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Thumbnail"))
        self.label_21.setText(_translate("MainWindow", "Default Size"))
        self.label_22.setText(_translate("MainWindow", "Custom Size"))
        self.radio_default_size.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Default resolution of the image will be used.</span></p></body></html>"))
        self.input_height.setPlaceholderText(_translate("MainWindow", "1"))
        self.input_width.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_23.setText(_translate("MainWindow", "Width"))
        self.label_24.setText(_translate("MainWindow", "Height"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_3), _translate("MainWindow", "Size"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Select resolution for images.</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "JPG "))
        self.label_26.setText(_translate("MainWindow", "JPEG"))
        self.label_27.setText(_translate("MainWindow", "PNG "))
        self.label_28.setText(_translate("MainWindow", "JFIF"))
        self.label_29.setText(_translate("MainWindow", "Default"))
        self.radio_default_format.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p>Default format of the image will be used.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_4), _translate("MainWindow", "Format"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_4), _translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Select image format</span></p></body></html>"))
        self.btn_apply_edits.setText(_translate("MainWindow", "Apply Edits"))
        self.btn_reset_stop.setText(_translate("MainWindow", "RESET"))
        self.compress_slider.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Select image quality</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "Quality"))
        self.compress_quality.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
